### ISSUE TITLE
Please include TimeLib.h

### ISSUE THREAD

**Issue by GanjaFarmer** [JChristensen/DS3232RTC#32] opened 2016-09-15 15:51 UTC
Hi,

There is an issue when compiling this library (and your TimeZone library too) for the latest ESP8266 Arduino core. It results in many errors.

To solve these errors, you must replace in DS3232RTC.h :
`#include <Time.h>`
by:
`#include <TimeLib.h>`

**Comment by jimmys01** [comment] 2016-09-16 23:09
True. Happened to me as well

**Comment by OneGneissGuy** [comment] 2017-03-09 22:51
Yes this line must be added.Has a pull request been made to address this?

**Comment by JChristensen** [comment] 2018-01-01 21:47
Duplicate of #30.

**Closed by JChristensen** 2018-01-01 21:47 UTC
Labels: duplicate
