### ISSUE TITLE
SetSerial does not compile

### ISSUE THREAD

**Issue by ieee488** [JChristensen/DS3232RTC#41] opened 2017-04-26 19:55 UTC
It requires <TimeLib.h> to compile

I found the answer at [https://forum.arduino.cc/index.php?topic=455832.0](url)

I am on Windows 10 Pro using Arduino IDE 1.8.2

**Comment by JChristensen** [comment] 2017-04-26 20:23
Duplicate of #32.

**Closed by JChristensen** 2017-04-26 20:23 UTC
Labels: duplicate
