### ISSUE TITLE
Unable to compile examples

### ISSUE THREAD

**Issue by Eheran1** [JChristensen/DS3232RTC#46] opened 2017-09-23 17:23 UTC
I was on Arduino IDE 1.6.x and now updated to 1.8.4 but that didnt help. Turns out you have to change "#include <Time.h>" to "#include <TimeLib.h>"
Otherwise this will be the error:
`In file included from C:\Users\*\Documents\Arduino\libraries\DS3232RTC-master\examples\TimeRTC\TimeRTC.ino:8:0:

C:\Users\*\Documents\Arduino\libraries\DS3232RTC-master/DS3232RTC.h:136:26: error: 'tmElements_t' has not been declared

         static byte read(tmElements_t &tm);

                          ^

C:\Users\*\Documents\Arduino\libraries\DS3232RTC-master/DS3232RTC.h:137:20: error: 'tmElements_t' has not been declared

         byte write(tmElements_t &tm);

                    ^

C:\Users\*\Documents\Arduino\libraries\DS3232RTC-master\examples\TimeRTC\TimeRTC.ino: In function 'void setup()':

TimeRTC:15: error: 'setSyncProvider' was not declared in this scope

     setSyncProvider(RTC.get);   // the function to get the time from the RTC

                            ^

TimeRTC:16: error: 'timeStatus' was not declared in this scope

     if(timeStatus() != timeSet) 

                   ^

TimeRTC:16: error: 'timeSet' was not declared in this scope

     if(timeStatus() != timeSet) 

                        ^

C:\Users\*\Documents\Arduino\libraries\DS3232RTC-master\examples\TimeRTC\TimeRTC.ino: In function 'void digitalClockDisplay()':

TimeRTC:31: error: 'hour' was not declared in this scope

     Serial.print(hour());

                       ^

TimeRTC:32: error: 'minute' was not declared in this scope

     printDigits(minute());

                        ^

TimeRTC:33: error: 'second' was not declared in this scope

     printDigits(second());

                        ^

TimeRTC:35: error: 'day' was not declared in this scope

     Serial.print(day());

                      ^

TimeRTC:37: error: 'month' was not declared in this scope

     Serial.print(month());

                        ^

TimeRTC:39: error: 'year' was not declared in this scope

     Serial.print(year()); 

                       ^

exit status 1
'setSyncProvider' was not declared in this scope
`

**Comment by JChristensen** [comment] 2018-01-01 21:46
Duplicate of #30.

**Closed by JChristensen** 2018-01-01 21:46 UTC
Labels: duplicate
